# Generated by Django 5.2.1 on 2025-05-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('reviews', models.TextField(blank=True, help_text='Clinic reviews')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviews',
            field=models.TextField(blank=True, help_text="Doctor's reviews about patients"),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='examination_notes',
            field=models.TextField(blank=True, help_text='Examination notes'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='test_results',
            field=models.TextField(blank=True, help_text='Save test results here'),
        ),
    ]
