# Generated by Django 5.2.1 on 2025-05-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
