# Generated by Django 5.2.1 on 2025-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_doctor_contact_info_doctor_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(choices=[('en', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian')], default='en', max_length=10),
        ),
    ]
